### ISSUE TITLE
#if USE_2812_INTERRUPTS throws an undefined error

### ISSUE THREAD

**Issue by sjoerdtimmer** [cnlohr/esp8266ws2812i2s#1]
You probably mean #ifdef USE_2812_INTERRUPTS?

Your repo didn't compile for me (conflicting copies of strcat so I probably have a different sdk setup).
So I tried to replace ws2812.c (from your other repo) in my current project with ws2812_i2s.c.
It compiles when I replace the #if with an #ifdef. (also copied ws2812_i2s.h and some other headers of course).

**Comment by cnlohr** [comment]
Hmm, the two repos work in a bit of a different way... I am afraid I don't really understand what you are changing.  Also, I have made a significant number of changes in the last few days including updating to the new SDK.  If you can, give it a shot.
