### ISSUE TITLE
Cant make it build

### ISSUE THREAD

**Issue by jonshouse1** [cnlohr/esp8266ws2812i2s#11]
I dont understand what I need to change to fix this ?  I am using the toolchain installed from this:
https://github.com/esp8266/esp8266-wiki/wiki/Toolchain

jon@esp8266dev:~/esp8266-examples/esp8266ws2812i2s$ make
~/esp-open-sdk/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc -mlongcalls -I/home/jon/esp-open-sdk/esp_iot_sdk_v1.5.2/include -Imyclib -Iinclude -Iuser -Os -I/home/jon/esp-open-sdk/esp_iot_sdk_v1.5.2/include/ -Icommon -DICACHE_FLASH driver/uart.c common/mystuff.c common/flash_rewriter.c common/http.c common/commonservices.c common/http_custom.c common/mdns.c common/mfs.c user/custom_commands.c user/ws2812_i2s.c user/user_main.c  -flto -nostdlib -Wl,--relax -Wl,--gc-sections -L/home/jon/esp-open-sdk/esp_iot_sdk_v1.5.2/lib -L~/esp-open-sdk/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/4.8.2/libgcc.a /home/jon/esp-open-sdk/esp_iot_sdk_v1.5.2/lib/liblwip.a /home/jon/esp-open-sdk/esp_iot_sdk_v1.5.2/lib/libssl.a /home/jon/esp-open-sdk/esp_iot_sdk_v1.5.2/lib/libupgrade.a /home/jon/esp-open-sdk/esp_iot_sdk_v1.5.2/lib/libnet80211.a /home/jon/esp-open-sdk/esp_iot_sdk_v1.5.2/lib/liblwip.a /home/jon/esp-open-sdk/esp_iot_sdk_v1.5.2/lib/libwpa.a /home/jon/esp-open-sdk/esp_iot_sdk_v1.5.2/lib/libnet80211.a /home/jon/esp-open-sdk/esp_iot_sdk_v1.5.2/lib/libphy.a /home/jon/esp-open-sdk/esp_iot_sdk_v1.5.2/lib/libcrypto.a /home/jon/esp-open-sdk/esp_iot_sdk_v1.5.2/lib/libmain.a /home/jon/esp-open-sdk/esp_iot_sdk_v1.5.2/lib/libpp.a ~/esp-open-sdk/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/4.8.2/libgcc.a -T /home/jon/esp-open-sdk/esp_iot_sdk_v1.5.2/ld/eagle.app.v6.ld -B/home/jon/esp-open-sdk/esp_iot_sdk_v1.5.2/lib -o image.elf
FW 0x00000.bin
/home/jon/esp-open-sdk/esptool/esptool.py -eo image.elf -bo 0x00000.bin -bs .text -bs .data -bs .rodata -bc -ec
usage: esptool [-h] [--port PORT] [--baud BAUD]
               {load_ram,dump_mem,read_mem,write_mem,write_flash,run,image_info,make_image,elf2image,read_mac,chip_id,flash_id,read_flash,verify_flash,erase_flash}
               ...
esptool: error: argument operation: invalid choice: 'image.elf' (choose from 'load_ram', 'dump_mem', 'read_mem', 'write_mem', 'write_flash', 'run', 'image_info', 'make_image', 'elf2image', 'read_mac', 'chip_id', 'flash_id', 'read_flash', 'verify_flash', 'erase_flash')
Makefile:72: recipe for target '0x00000.bin' failed
make: **\* [0x00000.bin] Error 2

**Comment by cnlohr** [comment]
Why open and close?  Please specify what you did to solve your problem so others can find out.  Was it an old version of esptool?

**Comment by jonshouse1** [comment]
I was being dumb, I failed to read the notes and put the absolute path of esptool into the FW_TOOL field in the makefile rather than building the required esptool utility and referencing it.  Basically I got confused as the two utilities have the same name.

**Comment by cnlohr** [comment]
I've improved the way this works anyway.  You should give it a shot now.
