### ISSUE TITLE
Doesn't seem to work at all, any debugging ideas?

### ISSUE THREAD

**Issue by nathanstitt** [cnlohr/esp8266ws2812i2s#12]
`esp8266ws2812i2s` seems like exactly what i'm looking for, a way to have the esp8266 be a dumb front-end to a bunch of WS2812 LED's.  Unfortunately I can't seem get the any output from it at all.  

I've successfully got it running on the esp8266 and can access the website.  When I run the `top` command, the website's LED display does cycle.

I've attempted to use both the `THREE` & `FOUR` sample types and have played with moving the `WS_I2S_BCK` up and down to no avail.

The fact that the LED's don't even flicker suggests to me that something's fundamentally mis-wired somewhere, but I am connecting the data-in line to the RX pin.  The LED's do work with the `neopixel` library on the same device, (but on different PIN).  I've had problems running `neopixel` in conjunction with network activity though, so I thought your library would be ideal.

Issue #2 mentions some debugging output.  Can you provide some hints on how to access that?  Since the serial RX port is busy with `I2S`, I don't think I can access the debug output that way.

Any idea's on other things to try?

**Comment by cnlohr** [comment]
WOAH Sorry I missed this!!! The RX port is not busy with serial debugging.  That's the TX port.  The RX port is TX on the programmer and should be unplugged from the programmer (or have a 4.7k+ resistor linking)  You can totally get debug data by watching serial at 115,200.

**Comment by nathanstitt** [comment]
Thanks @cnlohr !  That worked great - for some reason I thought the i2s was on the RX pin ;)
