### ISSUE TITLE
Safe to use?

### ISSUE THREAD

**Issue by ghost** [cnlohr/esp8266ws2812i2s#13]
Hi!

Quick question/remark, as issues cause I didn't see any contact details :)

Since this way of driving the WS2812's uses pin: RX1/(pin 25)/U0RXD/i2SO_DATA (lots of names for one pin :) ).
Which is also the RX pin when flashing the ESP8266.
Am I in any danger of breaking my ESP by flashing this firmware?

I'm worried about this because my serial interface might make it's TX high, at the same time the ESP boots with this firmware, which would set the pin as out and also make it high to set the leds to their initial state?

I'm not experienced enough to know if this is an issue or not, but I'm sure I remember never hooking up two outputs together ;)
Obviously once it's properly flashed I can remove the serial interface, and use OTA for further updates, but I'm worried about the short period inbetween :) Especially since I can't remember if the ESP reboots directly after flashing XD

Any suggestions/workarounds? :)
Thanks! :)

**Comment by cnlohr** [comment]
You're fine.  Only gotcha is to reflash the firmware you'll have to do the dance with the buttons.  Like hold GPIO0 low, hold reset, let go of reset, let go of GPIO0.  This'll put the chip in firmware mode.

The other gotcha is if the chip is hard-wired to the serial programmer, it will have a hard time driving the LED.  You're best off unplugging the programmer once flashed.

I don't use the normal OTA system.  You can drag-and-drop new flash into the webpage, though.  I just changed the way a lot of that works, so you can give that a whirl.

**Comment by ghost** [comment]
Just to be sure I started with a version which did not do WS2812 stuff, then OTA'd it, that worked ;)
Note that I'm only using the WS2812 part, in a different project with a different OTA.
And yeah, it's all breadboard, so no problem to unplug the serial chip after the first flash.
Sofar succes :)
