### ISSUE TITLE
I2S output does not look right

### ISSUE THREAD

**Issue by mroavi** [cnlohr/esp8266ws2812i2s#15]
Hi Charles. I compiled the project with no changes and flashed it to my board. I used the 'top' application to send packets to the module but none of the LEDs flashed. I used a logic analyzer to see the signal coming out of the U0RXD_U/I2S0_DATA pin. This is before sending running 'top':
![1](https://cloud.githubusercontent.com/assets/19517248/15454438/ecc3bc20-2038-11e6-9ea3-ffd9f8d31eb0.PNG)

Zoomed in pulse:
![2](https://cloud.githubusercontent.com/assets/19517248/15454447/2a20dab2-2039-11e6-9e01-382fabbc1976.PNG)

After running the 'top':
![3](https://cloud.githubusercontent.com/assets/19517248/15454473/aec6be08-2039-11e6-9e04-08e3089a81cb.PNG)

Any idea what the problem is?

**Comment by mroavi** [comment]
I noticed that you commented out the line that maps the I2SO_BCK to GPIO15:
`// PIN_FUNC_SELECT(PERIPHS_IO_MUX_MTDO_U, FUNC_I2SO_BCK);`

In order to check if the clock was working fine I included it back. This is how the clock looks like:
![image](https://cloud.githubusercontent.com/assets/19517248/15454624/ae32abf0-203e-11e6-921f-5d3d5613f015.png)
which actually looks fine to me.

The funny thing is that after doing this change (mapping the clock to GPIO15), the signal coming out U0RXD_U/I2S0_DATA also changed:
![image](https://cloud.githubusercontent.com/assets/19517248/15454632/da7843c8-203e-11e6-85db-03665a1654d7.png)

Zoom in:
![image](https://cloud.githubusercontent.com/assets/19517248/15454634/fa7331a6-203e-11e6-9040-f4d4724fc6b7.png)

Unfortunately, the LEDs are still not flashing.

Any thoughts?

**Comment by cnlohr** [comment]
That signal looks pretty awful.  Sadly, this is a situation where you might need a scope, but only after checking for things like ground loops, etc.  This is some pretty intense ringing on the line!

**Comment by mroavi** [comment]
I think I know what is going on, but I"m not 100% sure. I'm using an Adafruit HUZZAH ESP8266 breakout board. I just read from their webpage that there is a level shifter connected to the RX pin. Could this be why the I2S does not work properly?

**Comment by cnlohr** [comment]
Woah, that could totally mess it up.  I wish more people used resistors on their output pins... It is possible the level shifter could be driving the esp, very hard and would totally prevent all outbound communications.

**Comment by mroavi** [comment]
I replaced the Adafruit HUZZAH ESP8266 breakout board with a D1 Mini and it worked great. I definitely think that it is the level shifter what is interfering with the proper operation of the I2S. Thanks for your help!

**Comment by cnlohr** [comment]
Yeah, level shifters are almost always bad news bears.  People need to use resistor dividers much more often, especially if it's not 100% clear if something's an input or an output.
