### ISSUE TITLE
mDNS not working

### ISSUE THREAD

**Issue by bedenko** [cnlohr/esp8266ws2812i2s#2]
i installed latest version and compiled with SDK 1.4.0, but i am unable to get mDNS to advertise.
this is my output:

```
esp8266 ws2812 driver
Settings Loaded: ESP_9E5F33 / Default
Opmode: 1
Station mode: "SSID":"pass" (bssid_set:0)
IGMP Joining: b60aa8c0 fb0000e0
STAT: 5
IP: 192.168.10.182
NM: 255.255.255.0
GW: 192.168.10.1
WCFG: /SSID/pass/
IGMP Joining: b60aa8c0 
```

So i see that **JoinGropMDNS()** was called but i cant find advertisement with commad **avahi-browse -at** from another linux station.

**Comment by cnlohr** [comment]
I can certainly get that particular tool.  I was using a mobile-based tool to search, and making sure everything worked by default when you typed the address in or pinged it with the system.

**Comment by bedenko** [comment]
hm, 
the address really works (i.e. if i go to http://ESP_123456 i get resolved address),
but service discovery does not find the services being advertised.

Could [this line](https://github.com/cnlohr/esp8266ws2812i2s/blob/master/common/mdns.c#L355-L359) have to do anything with it?

**Comment by cnlohr** [comment]
I don't believe so. That is for responses to the ESP.  I was originally planning to use MDNS to let the ESPs find each other, however, that would take more resources than I'd like to spend.

**Comment by cnlohr** [comment]
@bedenko I know it's been a while, but, the footprint is much smaller now and everything seems to fit better.  I could probably do more to let mdns find services and whatnot and can debug now.  If you could tackle this issue, awesome if not I suppose I can give it a shot.

**Comment by cnlohr** [comment]
Ok!  MDNS was merged with esp82xx, and now everyhting's fixed.
