### ISSUE TITLE
Constant reboots on wsend

### ISSUE THREAD

**Issue by ghost** [cnlohr/esp8266ws2812i2s#23]
if I let wsend run and watch the usb serial port on 115200, I see the device reboot every time after it connects to the local wifi network and receives a udp packet from wsend.
on the webui however, it looks to do what it's supposed to without rebooting.

```
ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x40100000, len 32492, room 16
tail 12
chksum 0xf0
ho 0 tail 12 room 4
load 0x3ffe8000, len 884, room 12
tail 8
chksum 0x10
load 0x3ffe8380, len 2716, room 0
tail 12
chksum 0x39
csum 0x39
��r�l��H����2XX Web-GUI
Version: v0.5-14-g1d7d7-dev - Build sø. 11. sep. 00:13:34 +0200 2016 with -DICACHE_FLASH -DWEB_PORT=80 -DCOM_PORT=7777 -DBACKEND_PORT=7878  -DSLOWTICK_MS=5Loading Settings: af / 0 / 69 / 69
 Settings Loaded: ESP_881DBF / Default
Opmode: 1
Station mode: "MYSSID":"MYPASS" (bssid_set:0)
 Boot Ok.
IGMP Joining: 6b25a8c0 fb0000e0
 STAT: 5
IP: 192.168.37.107
NM: 255.255.255.0
GW: 192.168.37.1
WCFG: /MYSSID/MYPASS/
IGMP Joining: 6b25a8c0 fb0000e0
MFS Not found at regular address (ffffffff).
MFS Found at: 00010000
```

**Comment by con-f-use** [comment]
Does it only reboot, when `wsend` is running, or do you get random reboots on other occasions, too? Did you change the patterns in `pattern.c` in any way?

### Edit1:

I can actually reproduce this problem. For now I'd suggest, you roll pack to an older commit, where everything works. @cnlohr or I will get to the bottom of this. Though I won't until got a good night's sleep or two.

### Edit2:

It was actually a pretty simple fix involving a faulty `memcpy` destination. 39ecd7a did the trick.

**Comment by ghost** [comment]
Sweeet work, that was very fast :smile:

**Comment by con-f-use** [comment]
Had a hunch. Thanks for reporting, btw!

**Comment by ghost** [comment]
No problem at all, I'm a little of a fan of yours :smile:

**Comment by con-f-use** [comment]
Surely you mean @cnlohr, not @con-f-use, I'm just the janitor around here. ^^

**Comment by ghost** [comment]
heheeh, yes :laughing: you are correct

**Comment by cnlohr** [comment]
@con-f-use you keep saying that... mr. make wizard
