### ISSUE TITLE
Reboot sometimes when receiving network data

### ISSUE THREAD

**Issue by cnlohr** [cnlohr/esp8266ws2812i2s#25]
I just tried it out myself and it seems that sometimes when I send ws2812 network data, the ESP crashes and reboots.  This seems to happen frequently, every 2-3 seconds!  I'll look into it more tonight, but, it looks to be recent changes.  Anything @con-f-use  could have done?

**Comment by con-f-use** [comment]
Sry, can't reproduce. Tried with a NodeMCU and one of my esp-01s. Are you, by any chance, on the `dev` branch? I didn't propagate the hotfixes for #23 and #24 there (until f87a3e594f92714811749bdb9a7326163774aa7a). Maybe it's a number issue, I only tested with 10 LEDs.

**Comment by cnlohr** [comment]
OH SNAP. I didn't update.  Will check again tonight.

**Comment by cnlohr** [comment]
it works!
