### ISSUE TITLE
Timing values are used incorrectly

### ISSUE THREAD

**Issue by ghost** [cnlohr/esp8266ws2812i2s#27]
Hi!

I think the values for WS_I2S_BCK and WS_I2S_DIV are incorrect.
Currently -1 is subtracted from both before setting the values.
Instead they should be used as is.

The calculation given in the code for the frequency is:
`// 1600000000L/(div*bestbck)`, I assume there's one '0' too many :)
Which I would assume means:
160000000L / (WS_I2S_DIV * WS_I2S_BCK) = bit frequency in Hz

For an example I'll use WS2812_FOUR_SAMPLE, so:
#define WS_I2S_BCK 17
#define WS_I2S_DIV 4
And for the buffer sizes:
#define WS_BLOCKSIZE 4000
And 32 byte for the 'zero' buffer.
That's 4032 bytes for all the DMA buffers.

By triggering an interrupt on EOF on one of the buffers, I can quite accurately get the Hz of going through all the 4032 buffer bytes.
According to the caluculation and dividers this should be:
(160000000 / (4032 * 8) ) / (4 * 17) = 4960.317 / (4 * 17) = 72.94584500466853 Hz
But the value I measure is close to 103.3 Hz..
Now If I use the '-1' values instead: 3 and 16 we get:
4960.317 / (3 * 16) = 103.3399470899471 Hz
Which is pretty much identical to the measured value :)

So my suggestion is to not subtract -1 of the two values, and then use:
#define WS_I2S_BCK 16
#define WS_I2S_DIV 3
Which are the actual values used.
And correct the comment with the formula to:
// 160000000L / ( WS_I2S_DIV * WS_I2S_BCK )

Cheers :)

**Comment by cnlohr** [comment]
Have you tested with the new timing?  

Additionally, since the faster timing works with virtually all LED types, perhaps we should keep it that way.  Speed is beneficial for a number of reasons including driving extra LEDs.  Maybe we should make a note about it?  Do you think this is too fast?

**Comment by ghost** [comment]
Ah, here's me being unclear again :) The suggestion is not to change the actual timings, since they do work fine, but just the constants used for the dividers, and how they are used :) That way the math is actually correct :)

So:

    #ifdef WS2812_THREE_SAMPLE
    #define WS_I2S_BCK 22  //Seems to work as low as 19, but is shakey at 18.
    #define WS_I2S_DIV 4
    #elif defined( WS2812_FOUR_SAMPLE ) || defined(SK6812)
    #define WS_I2S_BCK 17  //Seems to work as low as 14, shoddy at 13.
    #define WS_I2S_DIV 4
    #else

becomes 

    #ifdef WS2812_THREE_SAMPLE
    #define WS_I2S_BCK 21  //Seems to work as low as 18, but is shakey at 17.
    #define WS_I2S_DIV 3
    #elif defined( WS2812_FOUR_SAMPLE ) || defined(SK6812)
    #define WS_I2S_BCK 16  //Seems to work as low as 13, shoddy at 12.
    #define WS_I2S_DIV 3
    #else

AND

    (((WS_I2S_BCK-1)&I2S_BCK_DIV_NUM )<<I2S_BCK_DIV_NUM_S)|
    (((WS_I2S_DIV-1)&I2S_CLKM_DIV_NUM)<<I2S_CLKM_DIV_NUM_S));

becomes

    (((WS_I2S_BCK)&I2S_BCK_DIV_NUM )<<I2S_BCK_DIV_NUM_S)|
    (((WS_I2S_DIV)&I2S_CLKM_DIV_NUM)<<I2S_CLKM_DIV_NUM_S));

Doing that, calculating the resulting frequency based on the divider values actually comes to a correct and very accurate value :)

**Comment by cnlohr** [comment]
Oh, I see what you're saying.  Yes, I've noticed that in a different project and wasn't thinking.
