### ISSUE TITLE
Working --> Mem check fail --> Bootloop

### ISSUE THREAD

**Issue by ben-chain** [cnlohr/esp8266ws2812i2s#32]
Hey Charles-- love all your stuff!

Been using this project in one of my own for some months now.  In the beginning it was working fine, but recently I started getting some flickering.  I couldn't find any hardware issues so I plugged into the board and lo and behold it was crashing randomly.  Reflashed the firmware and it got stuck in a boot loop.  Figured it was a hardware malfunction and bought [a replacement.](https://www.amazon.com/HiLetgo-Version-NodeMCU-Internet-Development/dp/B010O1G1ES/ref=sr_1_3?ie=UTF8&qid=1501356374&sr=8-3&keywords=nodemcu)

On the new one, I flashed it and found it to be crashing with a "MEM CHECK FAIL" error-- but only when I sent it UDP packets above a certain size. SSID/wifi functionality was working fine.  I reflashed again and it too is now stuck in a boot loop.

These things were just sitting on a breadboard, in a setup which I had working great with 300+ lights for months.  Do you have any advice for me to track this down?  What should I look for to fix/what could be breaking it like this?

**Comment by con-f-use** [comment]
Do you use the most recent commit (i.e. did you bump the sumodule version of esp82xx) and follow the [troubleshooting ](https://github.com/cnlohr/esp82xx/blob/master/README.md#troubleshooting) section in the readme? There have been alot of buxfixes that were not yet propagated to ws2812i2s. It sounds like [Issue 53](https://github.com/cnlohr/esp82xx/issues/53) in esp82xx.

**Comment by cnlohr** [comment]
@benj0702 did it work out for you?  If you get a chance see if it still happens.

Don't forget to ```make initdefault```

**Comment by ben-chain** [comment]
Finally got to revisit this and make initdefault did the trick!!!  Thank you!!!
