### ISSUE TITLE
Noise from RX1

### ISSUE THREAD

**Issue by busti** [cnlohr/esp8266ws2812i2s#33]
When connecting a led strip to the required pin the leds light up in the expected pattern, but with a lot of noise.
Up to 10 leds are flickering random colors and the whole strip flickers off and on.

**Comment by con-f-use** [comment]
Power issue? Do you monitor the supply and led voltages?

**Comment by busti** [comment]
That was it. I was powering the leds from a lab supply but not the esp. My USB-Serial Converter probably can't deliver the required power.
I am sorry for opening an issue. Is there perhaps an irc channel for the esp82xx project or any other related to the project?

**Comment by con-f-use** [comment]
Yes, the esp typically takes ~80mA and up to 300mA at extreme bursts. Most serial converters use a linear regulator (to generate a 3.3V supply from 5V USB) that is not meant for that much load. Some even burn out.

As to the IRC-channel, this project is mostly @cnlohr 's baby and he is a very busy man. So no specfic channel would have  reasonable expectancy of being manned the majority of time, but the esp forum is usually every helpful and has some chat-rooms posted somewhere. If you find a good chat/resource, please tell us here and we will put it in the README. Thx!

**Comment by cnlohr** [comment]
@con-f-use thank you for being awesome.
