### ISSUE TITLE
NodeMCU

### ISSUE THREAD

**Issue by nistvan86** [cnlohr/esp8266ws2812i2s#4]
In your README.MD you are saying this uses the RX1 pin of the ESP8266 to shift out I2S bits.
Am i correct that this means that with any development boards where the USB serial bridge is hardwired (like. NodeMCU) I2S usage is impossible?

**Comment by cnlohr** [comment]
I honestly don't know.  I never got NodeMCU or Arduino working on my ESP.  It was just easier to use C and ESPTool or netflashing.  Though ESPTool uses the serial port, it requires a reboot to put it into program mode.  This means the pin can then be used for anything I want.

**Comment by nistvan86** [comment]
By NodeMCU i meant the NodeMCU development board: http://www.seeedstudio.com/depot/NodeMCU-v2-Lua-based-ESP8266-development-kit-p-2415.html
It has an USB-to-serial IC hardwired to the ESP.

But you have already answered this to me on YouTube. (in non-software-downloading mode it should work)

Thanks! Closing.

**Comment by TiEr92** [comment]
Hi nistvan86, 
did you get your NodeMCU to work properly?
Can you please help me, so i can get mine working too?

**Comment by cnlohr** [comment]
Can't program? or Can't drive once programmed?

**Comment by nistvan86** [comment]
@TiEr92 haven't got the time to try it out in the end. Can't help you, sorry :(

**Comment by TiEr92** [comment]
Hey, 
i got it working right at this moment. I used the USB-Connection to power the Node, but if i use the power in pins it is just working fine! 

Thank you for your effort! 

Its a nice project!
