### ISSUE TITLE
rough how-to would be great

### ISSUE THREAD

**Issue by Mofef** [cnlohr/esp8266ws2812i2s#7]
Hey cnlohr,

thanks for sharing your work!
I'm trying to get it to work on a ordinary esp-01 breakout board. What I did so far: 
- adjusting the paths in the Makefile to my system
- installing this Toolchain https://github.com/esp8266/esp8266-wiki/wiki/Toolchain (so far i only programmed the esp via arduino)
- run `make` and `make burn` in your repo

what works: flashing
what doesn't work: I get this via serial when i power up the esp

```
Fatal exception 0(IllegalInstructionCause):
epc1=0x40251c3f, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x40100000, len 30088, room 16 
tail 8
chksum 0x77
load 0x3ffe8000, len 876, room 0 
tail 12
chksum 0x5b
ho 0 tail 12 room 4
load 0x3ffe8370, len 2504, room 12 
tail 12
chksum 0x44
csum 0x44
don't use rtc mem data
Fatal exception �d
```

are you asuming certain other bin files flashed to other areas of the memory? which?

thanks again!

**Comment by ajvpot** [comment]
I'm also interested if this can be used with the Arudino environment for ESP8266.

**Comment by cnlohr** [comment]
Unfortunately, it cannot be used with the Arduino environment that I know of?  I only know how to update it using the esptool.  I actually tried to get the arduino environment working for myself and never was able to get it running :-/

If anyone else could figure this out, I'd be appreciative too.
